In [94]:
import numpy as np
import pandas as pd
import reverse_geocoder as rg 
import pprint 
from datetime import datetime,time, date
import requests
import networkx as nx
import json
import matplotlib.pyplot as plt
from math import radians, cos, sin, asin, sqrt
import time

In [95]:
trip_df = pd.read_csv('2016_june_cleaned.csv')

In [96]:
trip_df.shape

(51607, 14)

In [97]:
trip_df = trip_df.rename(columns = {'Unnamed: 0': 'trip_id'})

In [98]:
trip_df.head()

,trip_id,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,dropoff_longitude,dropoff_latitude,payment_type,total_amount,dropoff_lat_long_tuple,dropoff_city
0,0,2016-06-01 00:00:55,2016-06-01 00:31:25,1,19.20,-73.790199,40.646770,2,-73.966484,40.789272,1,66.34,"(40.78927230834961, -73.96648406982422)",Manhattan
1,1,2016-06-01 00:01:35,2016-06-01 00:34:08,1,18.52,-73.789909,40.646751,2,-73.962631,40.801632,1,58.34,"(40.80163192749024, -73.96263122558594)",Manhattan
2,2,2016-06-01 00:01:56,2016-06-01 00:34:33,1,21.37,-73.782372,40.644585,2,-73.979279,40.776905,1,70.01,"(40.77690505981445, -73.97927856445312)",Manhattan
3,3,2016-06-01 00:02:36,2016-06-01 00:33:02,1,16.91,-73.789429,40.646759,2,-73.979111,40.766800,1,63.36,"(40.76679992675781, -73.97911071777342)",Manhattan
4,4,2016-06-01 00:03:54,2016-06-01 00:31:41,1,17.40,-73.789833,40.646851,2,-73.971542,40.762051,1,72.96,"(40.7620506286621, -73.97154235839844)",Manhattan

In [99]:
trip_df['language'] = 1

In [100]:
trip_df['profession'] = 1

In [101]:
v = trip_df['language'] == 1
trip_df.loc[v,'language'] = np.random.choice((0,1), v.sum(), p=(0.5,0.5))

In [102]:
v = trip_df['profession'] == 1
trip_df.loc[v,'profession'] = np.random.choice((0,1), v.sum(), p=(0.5,0.5))

In [103]:
trip_df.tail()

,trip_id,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,dropoff_longitude,dropoff_latitude,payment_type,total_amount,dropoff_lat_long_tuple,dropoff_city,language,profession
51602,51602,2016-06-30 23:56:12,2016-07-01 00:33:46,2,17.60,-73.782288,40.644569,2,-73.980667,40.764435,2,52.80,"(40.76443481445313, -73.98066711425781)",Manhattan,1,0
51603,51603,2016-06-30 23:59:04,2016-07-01 00:58:31,2,18.10,-73.781990,40.644711,2,-73.986450,40.758171,1,69.99,"(40.75817108154297, -73.9864501953125)",Manhattan,0,0
51604,51604,2016-06-30 23:59:20,2016-07-01 00:45:34,1,21.22,-73.790337,40.646629,2,-73.984230,40.779942,2,58.34,"(40.77994155883789, -73.9842300415039)",Manhattan,0,0
51605,51605,2016-06-30 23:59:53,2016-07-01 00:32:22,1,16.70,-73.789238,40.646832,2,-73.972740,40.764446,2,52.80,"(40.76444625854492, -73.97274017333984)",Manhattan,1,1
51606,51606,2016-06-30 23:59:54,2016-07-01 00:39:51,2,17.90,-73.784592,40.648472,2,-73.974915,40.758846,2,58.34,"(40.75884628295898, -73.97491455078125)",Manhattan,1,0

In [104]:
all_trips_sum = sum(trip_df.trip_distance)

In [105]:
trip_df.tpep_pickup_datetime = trip_df.tpep_pickup_datetime.apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S"))
trip_df.tpep_dropoff_datetime = trip_df.tpep_dropoff_datetime.apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S"))
trip_df = trip_df.sort_values(by = 'tpep_pickup_datetime')
trip_df.head()

,trip_id,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,dropoff_longitude,dropoff_latitude,payment_type,total_amount,dropoff_lat_long_tuple,dropoff_city,language,profession
0,0,2016-06-01 00:00:55,2016-06-01 00:31:25,1,19.20,-73.790199,40.646770,2,-73.966484,40.789272,1,66.34,"(40.78927230834961, -73.96648406982422)",Manhattan,0,1
1,1,2016-06-01 00:01:35,2016-06-01 00:34:08,1,18.52,-73.789909,40.646751,2,-73.962631,40.801632,1,58.34,"(40.80163192749024, -73.96263122558594)",Manhattan,1,1
2,2,2016-06-01 00:01:56,2016-06-01 00:34:33,1,21.37,-73.782372,40.644585,2,-73.979279,40.776905,1,70.01,"(40.77690505981445, -73.97927856445312)",Manhattan,0,1
3,3,2016-06-01 00:02:36,2016-06-01 00:33:02,1,16.91,-73.789429,40.646759,2,-73.979111,40.766800,1,63.36,"(40.76679992675781, -73.97911071777342)",Manhattan,0,1
4,4,2016-06-01 00:03:54,2016-06-01 00:31:41,1,17.40,-73.789833,40.646851,2,-73.971542,40.762051,1,72.96,"(40.7620506286621, -73.97154235839844)",Manhattan,1,0

In [106]:
trip_df.head()

,trip_id,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,dropoff_longitude,dropoff_latitude,payment_type,total_amount,dropoff_lat_long_tuple,dropoff_city,language,profession
0,0,2016-06-01 00:00:55,2016-06-01 00:31:25,1,19.20,-73.790199,40.646770,2,-73.966484,40.789272,1,66.34,"(40.78927230834961, -73.96648406982422)",Manhattan,0,1
1,1,2016-06-01 00:01:35,2016-06-01 00:34:08,1,18.52,-73.789909,40.646751,2,-73.962631,40.801632,1,58.34,"(40.80163192749024, -73.96263122558594)",Manhattan,1,1
2,2,2016-06-01 00:01:56,2016-06-01 00:34:33,1,21.37,-73.782372,40.644585,2,-73.979279,40.776905,1,70.01,"(40.77690505981445, -73.97927856445312)",Manhattan,0,1
3,3,2016-06-01 00:02:36,2016-06-01 00:33:02,1,16.91,-73.789429,40.646759,2,-73.979111,40.766800,1,63.36,"(40.76679992675781, -73.97911071777342)",Manhattan,0,1
4,4,2016-06-01 00:03:54,2016-06-01 00:31:41,1,17.40,-73.789833,40.646851,2,-73.971542,40.762051,1,72.96,"(40.7620506286621, -73.97154235839844)",Manhattan,1,0

In [107]:
trip_df.tail()

,trip_id,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,dropoff_longitude,dropoff_latitude,payment_type,total_amount,dropoff_lat_long_tuple,dropoff_city,language,profession
51602,51602,2016-06-30 23:56:12,2016-07-01 00:33:46,2,17.60,-73.782288,40.644569,2,-73.980667,40.764435,2,52.80,"(40.76443481445313, -73.98066711425781)",Manhattan,1,0
51603,51603,2016-06-30 23:59:04,2016-07-01 00:58:31,2,18.10,-73.781990,40.644711,2,-73.986450,40.758171,1,69.99,"(40.75817108154297, -73.9864501953125)",Manhattan,0,0
51604,51604,2016-06-30 23:59:20,2016-07-01 00:45:34,1,21.22,-73.790337,40.646629,2,-73.984230,40.779942,2,58.34,"(40.77994155883789, -73.9842300415039)",Manhattan,0,0
51605,51605,2016-06-30 23:59:53,2016-07-01 00:32:22,1,16.70,-73.789238,40.646832,2,-73.972740,40.764446,2,52.80,"(40.76444625854492, -73.97274017333984)",Manhattan,1,1
51606,51606,2016-06-30 23:59:54,2016-07-01 00:39:51,2,17.90,-73.784592,40.648472,2,-73.974915,40.758846,2,58.34,"(40.75884628295898, -73.97491455078125)",Manhattan,1,0

In [108]:
# trip_df['pickup_date'] = trip_df.tpep_pickup_datetime.apply(lambda date_time: date_time.date())
# trip_df['pickup_time'] = trip_df.tpep_pickup_datetime.apply(lambda date_time: date_time.time())

In [109]:
trip_df = trip_df[(trip_df.tpep_pickup_datetime >= datetime(2016, 6, 10, 8,0,0)) 
                  & (trip_df.tpep_pickup_datetime <= datetime(2016, 6, 10, 22,0,0))]

In [110]:
total_trips = trip_df.shape[0]

In [111]:
B_hdist = []
averageSpeed = None
B_tuple = None
allRouteDistance = dict()
totalRouteDistance = 0

In [112]:
# Pooling Window = 5 mins

def getGroup(a,b):
    res = trip_df[((trip_df.tpep_pickup_datetime - b).apply(lambda x: (x.total_seconds() <= 600) & 
                                                          (x.total_seconds() > 0))) & (trip_df.trip_id != a)]
    return res.trip_id.values

In [113]:
trip_df["time"]=trip_df.tpep_dropoff_datetime-trip_df.tpep_pickup_datetime;
trip_df["time"] = trip_df["time"].apply(lambda x: x.days*24*60*60+x.seconds)  
trip_df = trip_df[trip_df["time"] != 0]
trip_df["speed"]=trip_df.trip_distance/trip_df["time"]
averageSpeed=trip_df["speed"].mean()
#print(averageSpeed)

In [114]:
def haversine(lon1, lat1, lon2, lat2):
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    # haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * asin(sqrt(a))
    r = 3956  # Radius of earth in kilometers. Use 3956 for miles
    return c * r

In [115]:
def timeAtoB(hdist):
    return hdist/averageSpeed;

In [116]:
def lowerBound(B_hdist, B_tuple):
    res=[]
    for i in range(len(B_tuple)):
        b=B_tuple[i]
        timeBDest=trip_df.tpep_dropoff_datetime[b-1]-trip_df.tpep_pickup_datetime[b-1];  
        timeBDest=timeBDest.days*24*60*60+timeBDest.seconds; 
        delay=.20*trip_df.trip_distance[b-1]
        lval=timeADest+timeAtoB(B_hdist[i])
        rval=timeBDest+delay

        if(lval < rval):
            res.append((a,b))
    return res

In [117]:
def startComputation(B_tuple, trip_id):
#     print("Calculating all haversine distances for B's") 
    hDistA=(haversine(trip_df.pickup_longitude[row.trip_id],trip_df.pickup_latitude[row.trip_id],trip_df.dropoff_longitude[row.trip_id],trip_df.dropoff_latitude[row.trip_id]))
    for b in B_tuple:
        B_hdist.append(abs(haversine(trip_df.pickup_longitude[b-1],trip_df.pickup_latitude[b-1],trip_df.dropoff_longitude[b-1],trip_df.dropoff_latitude[b-1])-hDistA)) 
#     print(B_hdist)
    
#     print("Applying lower bound. Find the answer below:")
    result = lowerBound(B_hdist, B_tuple)
#     print(result)
    return result

In [118]:
def getActualDistance(tuple_list):
    
    result = []    #(drop-off_A_trip_id, drop-off_B_trip_id, actual distance from drop_off_A to drop-off_B)
    
    for pair in tuple_list:
        url = "https://graphhopper.com/api/1/matrix?"
        points = "point="+str(trip_df.loc[pair[0], "dropoff_latitude"])+","+str(trip_df.loc[pair[0], "dropoff_longitude"])
        points += "&point="+str(trip_df.loc[pair[1], "dropoff_latitude"])+","+str(trip_df.loc[pair[1], "dropoff_longitude"])
        url += points
        url+="&type=json&vehicle=car&debug=true&out_array=weights&out_array=times&out_array=distances&key=30796bf7-65cb-4a05-a43c-2c703f64cb8f"
        response = requests.get(url)
        response_dict = json.loads(response.text)
#         print(response.text)
#         print(response_dict['distances'])
        actual_dist = response_dict['distances'][0][1] * 0.000621371    # 1 meter = 0.000621371 miles
#         print(actual_dist)    
        result.append((pair[0], pair[1], actual_dist, trip_df.trip_distance[pair[0]], trip_df.trip_distance[pair[1]], trip_df.language[pair[0]], trip_df.language[pair[1]], trip_df.profession[pair[0]], trip_df.profession[pair[1]]))
    
    return result

In [119]:
def getSocialScore(prof1, prof2, lang1, lang2):
    if lang1== lang2:
        if prof1 == prof2:
            return 1
        else:
            return 0.6
    else:
        return 0.1

In [120]:
def getDistanceSaved(distance1, distance2, routeDistance):
    dist = (distance1+distance2) - routeDistance
    return dist

In [121]:
def getWeight(distSaved, socialScore):
    weight = (0.8*distSaved) + (0.2*socialScore)
    return round(weight,3)

In [122]:
trips_covered = set()

total_sum = 0

trips_merged = []



start_time = time.time()


for i,row in trip_df.iterrows():
    print("********___" + str(row.trip_id) + "___**********")
    timeADest = row.tpep_dropoff_datetime - row.tpep_pickup_datetime
    timeADest = timeADest.days*24*60*60+timeADest.seconds
    a=row.trip_id
#     print("Getting all Bs")
    B_tuple= getGroup(row.trip_id, row.tpep_pickup_datetime)
#     print(B_tuple)
    B_tuple = [val for val in B_tuple if val not in trips_covered]
    tuple_list = startComputation(B_tuple, row.trip_id)
    actual_dist_values = getActualDistance(tuple_list)
    actual_dist_values     # in miles
    if(len(actual_dist_values) != 0):
        T = np.append(a, B_tuple).tolist()
        linkWeights = []
        for row in actual_dist_values:
            distanceA = row[3]
            distanceB = row[4]
            routeDistance = row[2] + row[3]
            prof1 = row[7]
            prof2 = row[8]
            lang1 = row[5]
            lang2 = row[6]
            allRouteDistance[row[0],row[1]] = routeDistance
            
            socialScore = getSocialScore(prof1, prof2, lang1, lang2)
            distanceSaved = getDistanceSaved(distanceA, distanceB, routeDistance)
            if distanceSaved >= 0:
                finalWeight = getWeight(distanceSaved, socialScore)
                linkWeights.append((row[0], row[1], finalWeight))
#         print(linkWeights)
        if (len(linkWeights) != 0):
            G = nx.Graph()
            G.add_nodes_from(T)
            for link in linkWeights:
                G.add_edge(link[0], link[1], weight=link[2])

#             nx.draw(G, with_labels=True)
            M_max = nx.max_weight_matching(G, weight='weight')
#             print(M_max)
            list_M_max = list(M_max)
    

#             print(allRouteDistance)
            for l in list_M_max:
#                 print(l)
#                 print(type)
                if allRouteDistance.get(l):
                    totalRouteDistance += round(float(allRouteDistance.get(l)), 2)
                else:
                    totalRouteDistance += round(float(allRouteDistance.get(l[::-1])), 2)
#                     totalRouteDistance += float(allRouteDistance.get(l[::-1]))
        
#             print(list_M_max)
            trips_merged.append(list_M_max)
#             
            trips_covered.add(list_M_max[0][0])
            trips_covered.add(list_M_max[0][1])
            total_sum += trip_df.trip_distance[list_M_max[0][0]]
            total_sum += trip_df.trip_distance[list_M_max[0][1]]
        
        
        
#             print(trips_merged)
#             print(totalRouteDistance)
end_time = time.time()

# print(trips_merged)
# print(totalRouteDistance)

********___16303___**********
********___16304___**********
********___16305___**********
********___16306___**********
********___16307___**********
********___16308___**********
********___16309___**********
********___16310___**********
********___16311___**********
********___16312___**********
********___16313___**********
********___16314___**********
********___16315___**********
********___16316___**********
********___16317___**********
********___16318___**********
********___16319___**********
********___16320___**********
********___16321___**********
********___16322___**********
********___16323___**********
********___16324___**********
********___16325___**********
********___16326___**********
********___16327___**********
********___16328___**********
********___16329___**********
********___16330___**********
********___16331___**********
********___16332___**********
********___16333___**********
********___16334___**********
********___16335___**********
********___16336___**********
********___16337___**********
********___16338___**********
********___16339___**********
********___16340___**********
********___16341___**********
********___16342___**********
********___16343___**********
********___16344___**********
********___16345___**********
********___16346___**********
********___16347___**********
********___16348___**********
********___16349___**********
********___16350___**********
********___16351___**********
********___16352___**********
********___16353___**********
********___16354___**********
********___16355___**********
********___16356___**********
********___16357___**********
********___16358___**********
********___16359___**********
********___16360___**********
********___16361___**********
********___16362___**********
********___16363___**********
********___16364___**********
********___16365___**********
********___16366___**********
********___16367___**********
********___16368___**********
********___16369___**********
********___16370___**********
********___16371___**********
********___16372___**********
********___16373___**********
********___16374___**********
********___16375___**********
********___16376___**********
********___16377___**********
********___16378___**********
********___16379___**********
********___16380___**********
********___16381___**********
********___16382___**********
********___16383___**********
********___16384___**********
********___16385___**********
********___16386___**********
********___16387___**********
********___16388___**********
********___16389___**********
********___16390___**********
********___16391___**********
********___16392___**********
********___16393___**********
********___16394___**********
********___16395___**********
********___16396___**********
********___16397___**********
********___16398___**********
********___16399___**********
********___16400___**********
********___16401___**********
********___16402___**********
********___16403___**********
********___16404___**********
********___16405___**********
********___16406___**********
********___16407___**********
********___16408___**********
********___16409___**********
********___16410___**********
********___16411___**********
********___16412___**********
********___16413___**********
********___16414___**********
********___16415___**********
********___16416___**********
********___16417___**********
********___16418___**********
********___16419___**********
********___16420___**********
********___16421___**********
********___16422___**********
********___16423___**********
********___16424___**********
********___16425___**********
********___16426___**********
********___16427___**********
********___16428___**********
********___16429___**********
********___16430___**********
********___16431___**********
********___16432___**********
********___16433___**********
********___16434___**********
********___16435___**********
********___16436___**********
********___16437___**********
********___16438___**********
********___16439___**********
********___16440___**********
********___16441___**********
********___16442___**********
********___16443___**********
********___16444___**********
********___16445___**********
********___16446___**********
********___16447___**********
********___16448___**********
********___16449___**********
********___16450___**********
********___16451___**********
********___16452___**********
********___16453___**********
********___16454___**********
********___16455___**********
********___16456___**********
********___16457___**********
********___16458___**********
********___16459___**********
********___16460___**********
********___16461___**********
********___16462___**********
********___16463___**********
********___16464___**********
********___16465___**********
********___16466___**********
********___16467___**********
********___16468___**********
********___16469___**********
********___16470___**********
********___16471___**********
********___16472___**********
********___16473___**********
********___16474___**********
********___16475___**********
********___16476___**********
********___16478___**********
********___16477___**********
********___16479___**********
********___16480___**********
********___16481___**********
********___16482___**********
********___16483___**********
********___16484___**********
********___16485___**********
********___16486___**********
********___16487___**********
********___16488___**********
********___16489___**********
********___16490___**********
********___16491___**********
********___16492___**********
********___16493___**********
********___16494___**********
********___16495___**********
********___16496___**********
********___16497___**********
********___16498___**********
********___16499___**********
********___16500___**********
********___16501___**********
********___16502___**********
********___16503___**********
********___16504___**********
********___16505___**********
********___16506___**********
********___16507___**********
********___16508___**********
********___16509___**********
********___16510___**********
********___16511___**********
********___16512___**********
********___16513___**********
********___16514___**********
********___16515___**********
********___16516___**********
********___16517___**********
********___16518___**********
********___16519___**********
********___16520___**********
********___16521___**********
********___16522___**********
********___16523___**********
********___16524___**********
********___16525___**********
********___16526___**********
********___16527___**********
********___16528___**********
********___16529___**********
********___16530___**********
********___16531___**********
********___16532___**********
********___16533___**********
********___16534___**********
********___16535___**********
********___16536___**********
********___16537___**********
********___16538___**********
********___16539___**********
********___16540___**********
********___16541___**********
********___16542___**********
********___16543___**********
********___16544___**********
********___16545___**********
********___16546___**********
********___16547___**********
********___16548___**********
********___16549___**********
********___16550___**********
********___16551___**********
********___16552___**********
********___16553___**********
********___16554___**********
********___16555___**********
********___16556___**********
********___16557___**********
********___16558___**********
********___16559___**********
********___16560___**********
********___16561___**********
********___16562___**********
********___16563___**********
********___16564___**********
********___16565___**********
********___16566___**********
********___16567___**********
********___16568___**********
********___16569___**********
********___16570___**********
********___16571___**********
********___16572___**********
********___16573___**********
********___16574___**********
********___16575___**********
********___16576___**********

********___16577___**********
********___16578___**********
********___16579___**********
********___16580___**********
********___16581___**********
********___16582___**********
********___16583___**********
********___16584___**********
********___16585___**********
********___16586___**********
********___16587___**********
********___16588___**********
********___16589___**********
********___16590___**********
********___16591___**********
********___16592___**********
********___16593___**********
********___16594___**********
********___16595___**********
********___16596___**********
********___16597___**********
********___16598___**********
********___16599___**********
********___16600___**********
********___16601___**********
********___16602___**********
********___16603___**********
********___16604___**********
********___16605___**********
********___16606___**********
********___16607___**********
********___16608___**********
********___16609___**********
********___16610___**********
********___16611___**********
********___16612___**********
********___16613___**********
********___16614___**********
********___16615___**********
********___16616___**********
********___16617___**********
********___16618___**********
********___16619___**********
********___16620___**********
********___16621___**********
********___16622___**********
********___16623___**********
********___16624___**********
********___16625___**********
********___16626___**********
********___16627___**********
********___16628___**********
********___16630___**********
********___16629___**********
********___16631___**********
********___16632___**********
********___16633___**********
********___16634___**********
********___16635___**********
********___16636___**********
********___16637___**********
********___16638___**********
********___16639___**********
********___16640___**********
********___16641___**********
********___16642___**********
********___16643___**********
********___16644___**********
********___16645___**********
********___16646___**********
********___16647___**********
********___16648___**********
********___16649___**********
********___16650___**********
********___16651___**********
********___16652___**********
********___16653___**********
********___16654___**********
********___16655___**********
********___16656___**********
********___16657___**********
********___16658___**********
********___16659___**********
********___16660___**********
********___16661___**********
********___16662___**********
********___16663___**********
********___16664___**********
********___16665___**********
********___16666___**********
********___16667___**********
********___16668___**********
********___16669___**********
********___16670___**********
********___16671___**********
********___16672___**********
********___16673___**********
********___16674___**********
********___16675___**********
********___16676___**********
********___16677___**********
********___16678___**********
********___16679___**********
********___16680___**********
********___16681___**********
********___16682___**********
********___16683___**********
********___16684___**********
********___16685___**********
********___16686___**********
********___16687___**********
********___16688___**********
********___16689___**********
********___16690___**********
********___16691___**********
********___16692___**********
********___16693___**********
********___16694___**********
********___16695___**********
********___16696___**********
********___16697___**********
********___16698___**********
********___16699___**********
********___16700___**********
********___16701___**********
********___16702___**********
********___16703___**********
********___16704___**********
********___16705___**********
********___16706___**********
********___16707___**********
********___16708___**********
********___16709___**********
********___16710___**********
********___16711___**********
********___16712___**********
********___16713___**********
********___16714___**********
********___16715___**********
********___16716___**********
********___16717___**********
********___16718___**********
********___16719___**********
********___16720___**********
********___16721___**********
********___16722___**********
********___16723___**********
********___16724___**********
********___16725___**********
********___16726___**********
********___16727___**********
********___16728___**********
********___16729___**********
********___16730___**********
********___16731___**********
********___16732___**********
********___16733___**********
********___16734___**********
********___16735___**********
********___16736___**********
********___16737___**********
********___16738___**********
********___16739___**********
********___16740___**********
********___16741___**********
********___16742___**********
********___16743___**********
********___16744___**********
********___16745___**********
********___16746___**********
********___16747___**********
********___16748___**********
********___16749___**********
********___16750___**********
********___16751___**********
********___16752___**********
********___16753___**********
********___16754___**********
********___16755___**********
********___16756___**********
********___16757___**********
********___16758___**********
********___16759___**********
********___16760___**********
********___16761___**********
********___16762___**********
********___16763___**********
********___16764___**********
********___16765___**********
********___16766___**********
********___16767___**********
********___16768___**********
********___16769___**********
********___16770___**********
********___16771___**********
********___16772___**********
********___16773___**********
********___16774___**********
********___16775___**********
********___16776___**********
********___16777___**********
********___16778___**********
********___16779___**********
********___16780___**********
********___16781___**********
********___16782___**********
********___16783___**********
********___16784___**********
********___16785___**********
********___16786___**********
********___16787___**********
********___16788___**********
********___16789___**********
********___16790___**********
********___16791___**********
********___16792___**********
********___16793___**********
********___16794___**********
********___16795___**********
********___16796___**********
********___16797___**********
********___16798___**********
********___16799___**********
********___16800___**********
********___16801___**********
********___16802___**********
********___16803___**********
********___16804___**********
********___16805___**********
********___16806___**********
********___16807___**********
********___16808___**********
********___16809___**********
********___16810___**********
********___16811___**********
********___16812___**********
********___16813___**********
********___16814___**********
********___16815___**********
********___16816___**********
********___16817___**********
********___16818___**********
********___16819___**********
********___16820___**********
********___16821___**********
********___16822___**********
********___16823___**********
********___16824___**********
********___16825___**********
********___16826___**********
********___16827___**********
********___16828___**********
********___16829___**********
********___16830___**********
********___16831___**********
********___16832___**********
********___16833___**********
********___16834___**********
********___16835___**********
********___16836___**********
********___16837___**********
********___16838___**********
********___16839___**********
********___16840___**********
********___16841___**********
********___16842___**********
********___16843___**********
********___16844___**********
********___16845___**********
********___16846___**********
********___16847___**********
********___16848___**********
********___16849___**********
********___16850___**********

********___16851___**********
********___16852___**********
********___16853___**********
********___16854___**********
********___16855___**********
********___16856___**********
********___16857___**********
********___16858___**********
********___16859___**********
********___16860___**********
********___16861___**********
********___16862___**********
********___16863___**********
********___16864___**********
********___16865___**********
********___16866___**********
********___16867___**********
********___16868___**********
********___16869___**********
********___16870___**********
********___16871___**********
********___16872___**********
********___16873___**********
********___16874___**********
********___16875___**********
********___16876___**********
********___16877___**********
********___16878___**********
********___16879___**********
********___16880___**********
********___16881___**********
********___16882___**********
********___16883___**********
********___16884___**********
********___16885___**********
********___16886___**********
********___16887___**********
********___16888___**********
********___16889___**********
********___16890___**********
********___16891___**********
********___16892___**********
********___16893___**********
********___16894___**********
********___16895___**********
********___16896___**********
********___16897___**********
********___16898___**********
********___16899___**********
********___16900___**********
********___16901___**********
********___16902___**********
********___16903___**********
********___16904___**********
********___16905___**********
********___16906___**********
********___16907___**********
********___16908___**********
********___16909___**********
********___16910___**********
********___16911___**********
********___16912___**********
********___16913___**********
********___16914___**********
********___16915___**********
********___16916___**********
********___16917___**********
********___16918___**********
********___16919___**********
********___16920___**********
********___16921___**********
********___16922___**********
********___16923___**********
********___16924___**********
********___16925___**********
********___16926___**********
********___16927___**********
********___16928___**********
********___16929___**********
********___16930___**********
********___16931___**********
********___16932___**********
********___16933___**********
********___16934___**********
********___16935___**********
********___16936___**********
********___16937___**********
********___16938___**********
********___16939___**********
********___16940___**********
********___16941___**********
********___16942___**********
********___16943___**********
********___16944___**********
********___16945___**********
********___16946___**********
********___16947___**********
********___16948___**********
********___16949___**********
********___16950___**********
********___16951___**********
********___16952___**********
********___16953___**********
********___16954___**********
********___16955___**********
********___16956___**********
********___16957___**********
********___16958___**********
********___16959___**********
********___16960___**********
********___16961___**********
********___16962___**********
********___16963___**********
********___16964___**********
********___16965___**********
********___16966___**********
********___16967___**********
********___16968___**********
********___16969___**********
********___16970___**********
********___16971___**********
********___16972___**********
********___16973___**********
********___16974___**********
********___16975___**********
********___16976___**********
********___16977___**********
********___16978___**********
********___16979___**********
********___16980___**********
********___16981___**********
********___16982___**********
********___16983___**********
********___16984___**********
********___16985___**********
********___16986___**********
********___16987___**********
********___16988___**********
********___16989___**********
********___16990___**********
********___16991___**********
********___16992___**********
********___16993___**********
********___16994___**********
********___16995___**********
********___16996___**********
********___16997___**********
********___16998___**********
********___16999___**********
********___17000___**********
********___17001___**********
********___17002___**********
********___17003___**********
********___17004___**********
********___17005___**********
********___17006___**********
********___17007___**********
********___17008___**********
********___17009___**********
********___17010___**********
********___17011___**********
********___17012___**********
********___17013___**********
********___17014___**********
********___17015___**********
********___17016___**********
********___17017___**********
********___17018___**********
********___17019___**********
********___17020___**********
********___17021___**********
********___17022___**********
********___17023___**********
********___17024___**********
********___17025___**********
********___17026___**********
********___17027___**********
********___17028___**********
********___17029___**********
********___17030___**********
********___17031___**********
********___17032___**********
********___17033___**********
********___17034___**********
********___17035___**********
********___17036___**********
********___17037___**********
********___17038___**********
********___17039___**********
********___17040___**********
********___17041___**********
********___17042___**********
********___17043___**********
********___17044___**********
********___17045___**********
********___17046___**********
********___17047___**********
********___17048___**********
********___17049___**********
********___17050___**********
********___17051___**********
********___17052___**********
********___17053___**********
********___17054___**********
********___17055___**********
********___17056___**********
********___17057___**********
********___17058___**********
********___17059___**********
********___17060___**********
********___17061___**********
********___17062___**********
********___17063___**********
********___17064___**********
********___17065___**********
********___17066___**********
********___17067___**********
********___17068___**********
********___17069___**********
********___17070___**********
********___17071___**********
********___17072___**********
********___17073___**********
********___17074___**********
********___17075___**********
********___17076___**********
********___17077___**********
********___17078___**********
********___17079___**********
********___17080___**********
********___17081___**********
********___17082___**********
********___17083___**********
********___17084___**********
********___17085___**********
********___17086___**********
********___17087___**********
********___17088___**********
********___17089___**********
********___17090___**********
********___17091___**********
********___17092___**********
********___17093___**********
********___17094___**********
********___17095___**********
********___17096___**********
********___17097___**********
********___17098___**********
********___17099___**********
********___17100___**********
********___17101___**********
********___17102___**********
********___17103___**********
********___17104___**********
********___17105___**********
********___17106___**********
********___17107___**********
********___17108___**********
********___17109___**********
********___17110___**********
********___17111___**********
********___17112___**********
********___17113___**********
********___17114___**********
********___17115___**********
********___17116___**********
********___17117___**********
********___17118___**********
********___17119___**********
********___17120___**********
********___17121___**********
********___17122___**********
********___17123___**********
********___17124___**********
********___17125___**********
********___17126___**********

********___17127___**********
********___17128___**********
********___17129___**********
********___17130___**********
********___17131___**********
********___17132___**********
********___17133___**********
********___17134___**********
********___17135___**********
********___17136___**********
********___17137___**********
********___17138___**********
********___17139___**********
********___17140___**********
********___17141___**********
********___17142___**********
********___17143___**********
********___17144___**********
********___17145___**********
********___17146___**********
********___17147___**********
********___17148___**********
********___17149___**********
********___17150___**********
********___17151___**********
********___17152___**********
********___17153___**********
********___17154___**********
********___17155___**********
********___17156___**********
********___17157___**********
********___17158___**********
********___17159___**********
********___17160___**********
********___17161___**********
********___17162___**********
********___17163___**********
********___17164___**********
********___17165___**********
********___17166___**********
********___17167___**********
********___17168___**********
********___17169___**********
********___17170___**********
********___17171___**********
********___17172___**********
********___17173___**********
********___17174___**********
********___17175___**********
********___17176___**********
********___17177___**********
********___17178___**********
********___17179___**********
********___17180___**********
********___17181___**********
********___17182___**********
********___17183___**********
********___17184___**********
********___17185___**********
********___17186___**********
********___17187___**********
********___17188___**********
********___17189___**********
********___17190___**********
********___17191___**********
********___17192___**********
********___17193___**********
********___17194___**********
********___17195___**********
********___17196___**********
********___17197___**********
********___17198___**********
********___17199___**********
********___17200___**********
********___17201___**********
********___17202___**********
********___17203___**********
********___17204___**********
********___17205___**********
********___17206___**********
********___17207___**********
********___17208___**********
********___17209___**********
********___17210___**********
********___17211___**********
********___17212___**********
********___17213___**********
********___17214___**********
********___17215___**********
********___17216___**********
********___17217___**********
********___17218___**********
********___17219___**********
********___17220___**********
********___17221___**********
********___17222___**********
********___17223___**********
********___17224___**********
********___17225___**********
********___17226___**********
********___17227___**********
********___17228___**********
********___17229___**********
********___17230___**********
********___17231___**********
********___17232___**********
********___17233___**********
********___17234___**********
********___17235___**********
********___17236___**********
********___17237___**********
********___17238___**********
********___17239___**********
********___17240___**********
********___17241___**********
********___17242___**********
********___17243___**********
********___17244___**********
********___17245___**********
********___17246___**********
********___17247___**********
********___17248___**********
********___17249___**********
********___17250___**********
********___17251___**********
********___17252___**********
********___17253___**********
********___17254___**********
********___17255___**********
********___17256___**********
********___17257___**********
********___17258___**********
********___17259___**********
********___17260___**********
********___17261___**********
********___17262___**********
********___17263___**********
********___17264___**********
********___17265___**********
********___17266___**********
********___17267___**********
********___17268___**********
********___17269___**********
********___17270___**********
********___17271___**********
********___17272___**********
********___17273___**********
********___17274___**********
********___17275___**********
********___17276___**********
********___17277___**********
********___17278___**********
********___17279___**********
********___17280___**********
********___17281___**********
********___17282___**********
********___17283___**********
********___17284___**********
********___17285___**********
********___17286___**********
********___17287___**********
********___17288___**********
********___17289___**********
********___17290___**********
********___17291___**********
********___17292___**********
********___17293___**********
********___17294___**********
********___17295___**********
********___17296___**********
********___17297___**********
********___17298___**********
********___17299___**********
********___17300___**********
********___17301___**********
********___17302___**********
********___17303___**********
********___17304___**********
********___17305___**********
********___17306___**********
********___17307___**********
********___17308___**********
********___17309___**********
********___17310___**********
********___17311___**********
********___17312___**********
********___17313___**********
********___17314___**********
********___17315___**********
********___17316___**********
********___17317___**********
********___17318___**********
********___17319___**********
********___17320___**********
********___17321___**********
********___17322___**********
********___17323___**********
********___17324___**********
********___17325___**********
********___17326___**********
********___17327___**********
********___17328___**********
********___17329___**********
********___17330___**********
********___17331___**********
********___17332___**********
********___17333___**********
********___17334___**********
********___17335___**********
********___17336___**********
********___17337___**********
********___17338___**********
********___17339___**********
********___17340___**********
********___17341___**********
********___17342___**********
********___17343___**********
********___17344___**********
********___17345___**********
********___17346___**********
********___17347___**********
********___17348___**********
********___17349___**********
********___17350___**********
********___17351___**********
********___17352___**********
********___17353___**********
********___17354___**********
********___17355___**********
********___17356___**********
********___17357___**********
********___17358___**********
********___17359___**********
********___17360___**********
********___17361___**********
********___17362___**********
********___17363___**********
********___17364___**********
********___17365___**********
********___17366___**********
********___17367___**********
********___17368___**********
********___17369___**********
********___17370___**********
********___17371___**********
********___17372___**********
********___17373___**********
********___17374___**********
********___17375___**********
********___17376___**********
********___17377___**********
********___17378___**********
********___17379___**********
********___17380___**********
********___17381___**********
********___17382___**********
********___17383___**********
********___17384___**********
********___17385___**********
********___17386___**********
********___17387___**********
********___17388___**********
********___17389___**********
********___17390___**********
********___17391___**********
********___17392___**********
********___17393___**********
********___17394___**********
********___17395___**********
********___17396___**********
********___17397___**********
********___17398___**********
********___17399___**********
********___17400___**********

********___17401___**********
********___17402___**********
********___17403___**********
********___17404___**********
********___17405___**********
********___17406___**********
********___17407___**********
********___17408___**********
********___17409___**********
********___17410___**********
********___17411___**********
********___17412___**********
********___17413___**********
********___17414___**********
********___17415___**********
********___17416___**********
********___17417___**********
********___17418___**********
********___17419___**********
********___17420___**********
********___17421___**********
********___17422___**********
********___17423___**********
********___17424___**********
********___17425___**********
********___17426___**********
********___17427___**********
********___17428___**********
********___17429___**********
********___17430___**********
********___17431___**********
********___17432___**********
********___17433___**********
********___17434___**********
********___17435___**********
********___17436___**********
********___17437___**********
********___17438___**********
********___17439___**********
********___17440___**********
********___17441___**********
********___17442___**********
********___17443___**********
********___17444___**********
********___17445___**********
********___17446___**********
********___17447___**********
********___17448___**********
********___17449___**********
********___17450___**********
********___17451___**********
********___17452___**********
********___17453___**********
********___17454___**********
********___17455___**********
********___17456___**********
********___17457___**********
********___17458___**********
********___17459___**********
********___17460___**********
********___17461___**********
********___17462___**********
********___17463___**********
********___17464___**********
********___17465___**********
********___17466___**********
********___17467___**********
********___17468___**********
********___17469___**********
********___17470___**********
********___17471___**********
********___17472___**********
********___17473___**********
********___17474___**********
********___17475___**********
********___17476___**********
********___17477___**********
********___17478___**********
********___17479___**********
********___17480___**********
********___17481___**********
********___17482___**********
********___17483___**********
********___17484___**********
********___17485___**********
********___17486___**********
********___17487___**********
********___17488___**********
********___17489___**********
********___17490___**********
********___17491___**********
********___17492___**********
********___17493___**********
********___17494___**********
********___17495___**********
********___17496___**********
********___17497___**********
********___17498___**********
********___17499___**********
********___17500___**********
********___17501___**********
********___17502___**********
********___17503___**********
********___17504___**********
********___17505___**********
********___17506___**********
********___17507___**********
********___17508___**********
********___17509___**********
********___17510___**********
********___17511___**********
********___17512___**********
********___17513___**********
********___17514___**********
********___17515___**********
********___17516___**********
********___17517___**********
********___17518___**********
********___17519___**********
********___17520___**********
********___17521___**********
********___17522___**********
********___17523___**********
********___17524___**********
********___17525___**********
********___17526___**********
********___17527___**********
********___17528___**********
********___17529___**********
********___17530___**********
********___17531___**********
********___17532___**********
********___17533___**********
********___17534___**********
********___17535___**********
********___17536___**********
********___17537___**********
********___17538___**********
********___17539___**********
********___17540___**********
********___17541___**********
********___17542___**********
********___17543___**********
********___17544___**********
********___17545___**********
********___17546___**********
********___17547___**********
********___17548___**********
********___17549___**********
********___17550___**********
********___17551___**********
********___17552___**********
********___17553___**********
********___17554___**********
********___17555___**********
********___17556___**********
********___17557___**********
********___17558___**********
********___17559___**********
********___17560___**********
********___17561___**********
********___17562___**********
********___17563___**********
********___17564___**********
********___17565___**********
********___17566___**********
********___17567___**********
********___17568___**********
********___17569___**********
********___17570___**********
********___17571___**********
********___17572___**********
********___17573___**********
********___17574___**********
********___17575___**********
********___17576___**********
********___17577___**********
********___17578___**********
********___17579___**********
********___17580___**********
********___17581___**********
********___17582___**********
********___17583___**********
********___17584___**********
********___17585___**********
********___17586___**********
********___17587___**********
********___17588___**********
********___17589___**********
********___17590___**********
********___17591___**********
********___17592___**********

In [123]:
distanceSavedPercent = ((total_sum - totalRouteDistance) * 100)/ all_trips_sum

In [124]:
total_merged_trips = len(trips_covered)
tripsSavedPercent = (total_merged_trips*100)/(2*total_trips)

In [125]:
total_computation_time = end_time - start_time

In [126]:
print('distance saved: ', distanceSavedPercent)
print('trips saved: ', tripsSavedPercent)
print('computation time: ', total_computation_time)

('distance saved: ', 1.684959133921943)
('trips saved: ', 47)
('computation time: ', 3281.488440990448)

In [ ]:
# dist_plot = [distanceSavedPercent,  ]
# trip_plot = [tripsSavedPercent, ]